export const SEED_JOBS = [
  {
    id: 1,
    client: "Rodriguez Family",
    address: "482 Bergen Ave, Jersey City",
    type: "Residential",
    sqft: 2400,
    value: 380,
    status: "Pending Moon Review",
    fieldRep: "Jovan M.",
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    services: JSON.stringify(["Deep Clean", "Carpet"]),
    urgent: true,
    aiSummary:
      "2,400 sq ft residential. 3 bed, 2 bath, open-plan living. Carpet in all bedrooms shows heavy soil — extraction required. Hardwood in common areas moderate build-up. No mold detected.",
    aiFlags: JSON.stringify(["Bedroom 2: pet staining — pre-treatment likely needed"]),
    hours: 6.5,
    basePrice: 310,
    addons: 70,
    notes: null,
    billingName: null,
    billingEmail: null,
  },
  {
    id: 2,
    client: "Northside Medical Group",
    address: "91 Main St, Hackensack",
    type: "Commercial",
    sqft: 8200,
    value: 2100,
    status: "Estimate Sent",
    fieldRep: "Jovan M.",
    submittedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
    services: JSON.stringify(["Commercial", "Windows", "Floor Polish"]),
    urgent: false,
    aiSummary:
      "8,200 sq ft medical facility across 2 floors. Clinical areas require hospital-grade sanitization. Reception and admin areas moderate condition.",
    aiFlags: JSON.stringify([]),
    hours: 18,
    basePrice: 1800,
    addons: 300,
    notes: null,
    billingName: "Dr. Sarah Chen",
    billingEmail: "billing@northsidemedical.com",
  },
  {
    id: 3,
    client: "Airbnb — Park Slope Unit",
    address: "344 7th Ave, Brooklyn",
    type: "Airbnb",
    sqft: 950,
    value: 185,
    status: "Site Visit Submitted",
    fieldRep: "Paragon Team",
    submittedAt: new Date(Date.now() - 32 * 60 * 1000),
    services: JSON.stringify(["Airbnb Turnover"]),
    urgent: false,
    aiSummary:
      "950 sq ft Airbnb unit. Light turnover clean. Hardwood throughout, one bathroom, open kitchen. Previous guests departed this morning.",
    aiFlags: JSON.stringify([]),
    hours: 3,
    basePrice: 165,
    addons: 20,
    notes: null,
    billingName: null,
    billingEmail: null,
  },
  {
    id: 4,
    client: "Bergen County Schools",
    address: "110 State St, Hackensack",
    type: "Commercial",
    sqft: 24000,
    value: 5800,
    status: "Follow-Up",
    fieldRep: "Jovan M.",
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    services: JSON.stringify(["Commercial", "Post-Construction"]),
    urgent: true,
    aiSummary:
      "24,000 sq ft school facility across 3 floors. Post-construction debris throughout. Tile and epoxy flooring. 42 classrooms, 8 bathrooms, cafeteria, gymnasium.",
    aiFlags: JSON.stringify([
      "Gymnasium: adhesive residue requires specialist solvent",
      "3rd floor bathrooms: grout remediation needed",
    ]),
    hours: 38,
    basePrice: 4800,
    addons: 1000,
    notes: null,
    billingName: "Linda Torres",
    billingEmail: "ltorres@bergenschools.org",
  },
  {
    id: 5,
    client: "Kim Residence",
    address: "28 Maple Dr, Fair Lawn",
    type: "Residential",
    sqft: 1800,
    value: 295,
    status: "Closed Won",
    fieldRep: "Paragon Team",
    submittedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    services: JSON.stringify(["Deep Clean", "Grout"]),
    urgent: false,
    aiSummary:
      "1,800 sq ft residential. Standard deep clean. Tile grout throughout kitchen and two bathrooms requires treatment.",
    aiFlags: JSON.stringify([]),
    hours: 5,
    basePrice: 255,
    addons: 40,
    notes: null,
    billingName: null,
    billingEmail: null,
  },
  {
    id: 6,
    client: "Riverside Gym & Fitness",
    address: "600 River Rd, Edgewater",
    type: "Commercial",
    sqft: 6400,
    value: 1450,
    status: "AI Analysis in Progress",
    fieldRep: "Jovan M.",
    submittedAt: new Date(Date.now() - 14 * 60 * 1000),
    services: JSON.stringify(["Commercial", "Carpet", "Upholstery"]),
    urgent: false,
    aiSummary:
      "6,400 sq ft commercial gym. Rubber and carpet flooring. Locker rooms require full sanitization. Upholstery on 24 bench pads.",
    aiFlags: JSON.stringify(["Locker room drain clogged — flag to client before service"]),
    hours: 12,
    basePrice: 1200,
    addons: 250,
    notes: null,
    billingName: null,
    billingEmail: null,
  },
];
